development:
  adapter: postgresql
  encoding: unicode
  database: ember_careers_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: ember_careers_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: ember_careers_production
  pool: 5
  username:
  password:
