source 'https://rubygems.org'

gem 'rails', '4.0.4'
gem 'pg'
gem 'unicorn'
gem 'unicorn-rails'

gem 'sass-rails', '~> 4.0.2'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'

gem 'active_model_serializers'
gem 'omniauth-github'

group :development, :test do
  gem 'dotenv-rails'
  gem 'pry-rails'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'shoulda-matchers'
  gem 'valid_attribute'
  gem 'quiet_assets'
end

group :production do
  gem 'rails_12factor'
end
